apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.back.image }} 
  labels:
    app: {{ .Release.Name }}-{{ .Values.back.image }}
spec:
  replicas: {{ .Values.back.replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.back.image }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.back.image }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.back.image }} 
          image: {{ .Values.back.repo }}/{{ .Values.back.image }}:{{ .Values.back.tag }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.db }}
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.db }}
                  key: MYSQL_USER
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.db }}
                  key: MYSQL_DB
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.db }}
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 5001
              protocol: TCP
