apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.front.image }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.{{ .Values.ingress.domain }} # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.front.image }}-svc  # Replace with your frontend service name
                port:
                  number: {{ .Values.front.port }} # Match the service's exposed port