apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.front.image }}-svc
spec:
  type: ClusterIP 
  selector:
    app: {{ .Release.Name }}-{{ .Values.front.image }}
  ports:
    - port: {{ .Values.front.port }}
      targetPort: {{ .Values.front.port }}
