apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.environment }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "{{ .Values.global.chart.repo }}"
    targetRevision: "{{ .Values.global.chart.targetRevision }}"
    path: charts/app
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.environment }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
